spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/vhs-lab
        username: vhs-lab-user
        password: password

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
